# Generated by Django 3.2.8 on 2021-11-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('About', models.CharField(max_length=1000)),
                ('Media', models.FileField(default='', upload_to='uploads/')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('GroupMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
                ('GroupName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            options={
                'unique_together': {('GroupName', 'GroupMember')},
            },
        ),
    ]
