# Generated by Django 3.2.8 on 2021-11-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('GroupName', 'GroupMember')},
        ),
        migrations.AlterModelTable(
            name='groupmembership',
            table='group_groupmembership',
        ),
    ]
