# Generated by Django 3.2.9 on 2022-01-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_tbl',
            name='Age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='group_tbl',
            name='State',
            field=models.CharField(default='', max_length=100),
        ),
    ]
