# Generated by Django 3.2.8 on 2021-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Media',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
