# Generated by Django 3.2.8 on 2021-11-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20211115_1719'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupmembership',
            table=None,
        ),
    ]
