# Generated by Django 3.2.8 on 2021-12-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSoilTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilTag', models.CharField(max_length=150)),
                ('SoilTagGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            options={
                'unique_together': {('SoilTagGroup', 'soilTag')},
            },
        ),
        migrations.CreateModel(
            name='GroupPlantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantTag', models.CharField(max_length=150)),
                ('PlantTagGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            options={
                'unique_together': {('PlantTagGroup', 'plantTag')},
            },
        ),
    ]
