# Generated by Django 3.2.8 on 2021-11-15 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=150)),
                ('Study', models.CharField(blank=True, max_length=1000)),
                ('Lives', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
                ('Username', models.CharField(max_length=150)),
                ('Name', models.CharField(max_length=150)),
                ('DateOfBirth', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('District', models.CharField(max_length=150)),
                ('State', models.CharField(max_length=150)),
                ('Occupation', models.CharField(max_length=150)),
                ('About', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=1)),
                ('MaritalStatus', models.CharField(max_length=150)),
                ('UserLevel', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'login_person',
            },
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pictures', models.ImageField(upload_to='uploads/')),
                ('Species', models.CharField(max_length=150)),
                ('Types', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detail', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'SensorData',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('ranking', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=member.models.Users.upload_photo)),
                ('resume', models.ImageField(blank=True, null=True, upload_to=member.models.Users.upload_file)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
