# Generated by Django 3.2.8 on 2021-12-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttag',
            name='PlantTagName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='soiltag',
            name='SoilTagName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
