# Generated by Django 3.2.8 on 2021-12-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgrammeName', models.CharField(default='', max_length=150)),
                ('Speaker', models.CharField(default='', max_length=150)),
                ('Description', models.CharField(default='', max_length=150)),
                ('Date', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('PIC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.person')),
            ],
            options={
                'db_table': 'Workshop',
            },
        ),
        migrations.CreateModel(
            name='SoilTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilTag', models.CharField(max_length=150)),
                ('SoilTagWorkshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
            options={
                'unique_together': {('SoilTagWorkshop', 'soilTag')},
            },
        ),
        migrations.CreateModel(
            name='PlantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantTag', models.CharField(max_length=150)),
                ('PlantTagWorkshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
            options={
                'unique_together': {('PlantTagWorkshop', 'plantTag')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgrammeName', models.CharField(default='', max_length=150)),
                ('Date', models.DateField()),
                ('BookWorkshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
                ('Participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.person')),
            ],
            options={
                'unique_together': {('BookWorkshop', 'Participant')},
            },
        ),
    ]
