# Generated by Django 3.2.8 on 2021-11-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgrammeName', models.CharField(default='', max_length=150)),
                ('Description', models.CharField(default='', max_length=150)),
                ('Date', models.DateField()),
                ('Session', models.CharField(max_length=150)),
                ('PIC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.person')),
            ],
            options={
                'db_table': 'Workshop',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgrammeName', models.CharField(default='', max_length=150)),
                ('Date', models.DateField()),
                ('Session', models.CharField(max_length=150)),
                ('BookWorkshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
                ('Participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.person')),
            ],
            options={
                'unique_together': {('BookWorkshop', 'Participant')},
            },
        ),
    ]
