# Generated by Django 3.2.8 on 2022-01-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgrammeName', models.CharField(default='', max_length=150)),
                ('Speaker', models.CharField(default='', max_length=150)),
                ('Description', models.CharField(default='', max_length=150)),
                ('Date', models.DateField()),
                ('Gender', models.CharField(default='', max_length=20)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('State', models.CharField(default='', max_length=100)),
                ('Venue', models.CharField(default='', max_length=100)),
                ('PIC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.person')),
            ],
            options={
                'db_table': 'Workshop',
            },
        ),
        migrations.CreateModel(
            name='WorkshopSoilTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkshopSoilTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soilTagging', to='workshop.workshop')),
                ('soilTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.soiltag')),
            ],
            options={
                'unique_together': {('WorkshopSoilTag', 'soilTag')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopPlantTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkshopPlantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantTagging', to='workshop.workshop')),
                ('plantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.planttag')),
            ],
            options={
                'unique_together': {('WorkshopPlantTag', 'plantTag')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgrammeName', models.CharField(default='', max_length=150)),
                ('Date', models.DateField()),
                ('BookWorkshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
                ('Participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.person')),
            ],
            options={
                'unique_together': {('BookWorkshop', 'Participant')},
            },
        ),
    ]
