# Generated by Django 3.2.8 on 2021-12-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopPlantTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkshopPlantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantTagging', to='workshop.workshop')),
                ('plantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.planttag')),
            ],
            options={
                'unique_together': {('WorkshopPlantTag', 'plantTag')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopSoilTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkshopSoilTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soilTagging', to='workshop.workshop')),
                ('soilTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.soiltag')),
            ],
            options={
                'unique_together': {('WorkshopSoilTag', 'soilTag')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='soiltag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='soiltag',
            name='SoilTagWorkshop',
        ),
        migrations.DeleteModel(
            name='PlantTag',
        ),
        migrations.DeleteModel(
            name='SoilTag',
        ),
    ]
