# Generated by Django 3.2.8 on 2021-12-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantTag', models.CharField(max_length=150)),
                ('PlantTagWorkshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
            options={
                'unique_together': {('PlantTagWorkshop', 'plantTag')},
            },
        ),
    ]
