# Generated by Django 3.2.9 on 2022-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='Gender',
            field=models.CharField(default='', max_length=20),
        ),
    ]
