# Generated by Django 3.2.8 on 2021-11-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Session',
        ),
    ]
