# Generated by Django 3.2.8 on 2022-01-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20211216_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='State',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workshop',
            name='Venue',
            field=models.CharField(default='', max_length=100),
        ),
    ]
