# Generated by Django 3.2.8 on 2021-11-15 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=255)),
                ('Pictures', models.ImageField(upload_to='uploads/')),
                ('Video', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('Message', models.CharField(blank=True, max_length=255)),
                ('Photo', models.ImageField(upload_to='images/')),
                ('Video', models.FileField(null=True, upload_to='uploads/')),
                ('Graph', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            options={
                'db_table': 'Feed',
            },
        ),
    ]
