# Generated by Django 3.2.8 on 2021-11-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Graph',
        ),
    ]
