# Generated by Django 3.2.8 on 2021-12-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsoiltagging',
            name='FeedSoilTag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soilTagging', to='sharing.feed'),
        ),
    ]
