# Generated by Django 3.2.9 on 2022-01-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='Gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='feed',
            name='State',
            field=models.CharField(default='', max_length=100),
        ),
    ]
