# Generated by Django 3.2.8 on 2022-01-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20220119_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='Gender',
            new_name='Skill',
        ),
    ]
