# Generated by Django 3.2.8 on 2021-12-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_planttag'),
        ('sharing', '0002_alter_feedsoiltagging_feedsoiltag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPlantTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedPlantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantTagging', to='sharing.feed')),
                ('plantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.planttag')),
            ],
            options={
                'unique_together': {('FeedPlantTag', 'plantTag')},
            },
        ),
    ]
