# Generated by Django 3.2.8 on 2021-12-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20211227_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
