# Generated by Django 3.2.8 on 2021-12-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_auto_20211227_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
